var techActivities = [
    "Study quantum communication.",
"Get into tech in archaeoastronomy.",
"Experiment with tech in virtual chemistry labs.",
"Dive into tech in sustainable farming.",
"Learn about tech in electric vehicles.",
"Explore tech in eco-friendly building design.",
"Study tech in telemedicine.",
"Try your hand at tech in gene editing.",
"Dive into tech in artificial organs.",
"Get into tech in renewable energy storage.",
"Experiment with tech in hydroponics.",
"Study tech in urban planning.",
"Learn about tech in self-driving cars.",
"Dive into tech in drone technology.",
"Try your hand at tech in biometrics.",
"Explore tech in speech synthesis.",
"Study tech in sign language recognition.",
"Get into tech in wildlife tracking.",
"Dive into tech in botany research.",
"Try tech in marine biology research.",
"Explore tech in geology research.",
"Study tech in forestry research.",
"Try tech in environmental education research.",
"Explore tech in recycling research.",
"Dive into tech in sustainability research.",
"Get into tech in wildlife photography research.",
"Experiment with tech in ornithology research.",
"Learn about tech in meteorology research.",
"Dive into tech in climate science research.",
"Study tech in geological research.",
"Try tech in archaeological research.",
"Explore tech in astronomy research.",
"Dive into tech in physics research.",
"Get into tech in chemistry research.",
"Experiment with tech in biology research.",
"Learn about tech in psychology research.",
"Dive into tech in social sciences research.",
"Study tech in environmental research.",
"Try tech in neuroscience research.",
"Dive into tech in linguistics research.",
"Get into tech in history research.",
"Explore tech in literature research.",
"Dive into tech in art and culture research.",
"Try tech in political science research.",
"Study tech in economics research.",
"Experiment with tech in education research.",
"Learn about tech in sociology research.",
"Dive into tech in anthropology research.",
"Get into tech in philosophy research.",
"Explore tech in gender studies research.",
"Dive into tech in religious studies research.",
"Try tech in law research.",
"Study tech in business research.",
"Get into tech in communication research.",
"Dive into tech in journalism research.",
"Experiment with tech in marketing research.",
"Learn about tech in finance research.",
"Dive into tech in advertising research.",
"Get into tech in public relations research.",
"Experiment with tech in human resources research.",
"Dive into tech in project management research.",
"Get into tech in operations research.",
"Dive into tech in supply chain management research.",
"Try tech in quality management research.",
"Explore tech in data analysis research.",
"Dive into tech in data visualization research.",
"Get into tech in data mining research.",
"Experiment with tech in machine learning research.",
"Learn about tech in natural language processing research.",
"Dive into tech in artificial intelligence research.",
"Study tech in robotics research.",
"Try tech in computer vision research.",
"Dive into tech in pattern recognition research.",
"Explore tech in speech recognition research.",
"Get into tech in reinforcement learning research.",
"Experiment with tech in deep learning research.",
"Dive into tech in neural networks research.",
"Study tech in autonomous systems research.",
"Try tech in control systems research.",
"Dive into tech in mechatronics research.",
"Get into tech in sensor technology research.",
"Experiment with tech in actuators research.",
"Dive into tech in nanotechnology research.",
"Get into tech in materials science research.",
"Study tech in quantum computing research.",
"Try tech in cryptography research.",
"Explore tech in network security research.",
"Dive into tech in cloud computing research.",
"Get into tech in cybersecurity research.",
"Experiment with tech in computer forensics research.",
"Learn about tech in ethical hacking research.",
"Dive into tech in software development research.",
"Get into tech in web development research.",
"Dive into tech in app development research.",
"Experiment with tech in game development research.",
"Learn about tech in UI/UX design research.",
"Dive into tech in VR development research.",
"Experiment with tech in AR development research.",
"Learn about tech in 3D printing research.",
"Dive into tech in computer graphics research.",
"Get into tech in animation research.",
"Dive into tech in video game design research.",
"Try tech in sound design research.",
"Explore tech in video production research.",
"Dive into tech in photography research.",
"Get into tech in film production research.",
"Experiment with tech in digital marketing research.",
"Learn about tech in social media marketing research.",
"Dive into tech in SEO research.",
"Get into tech in email marketing research.",
"Experiment with tech in content marketing research.",
"Dive into tech in affiliate marketing research.",
"Try tech in online advertising research.",
"Explore tech in influencer marketing research.",
"Dive into tech in brand management research.",
"Get into tech in customer relationship management research.",
"Experiment with tech in e-commerce research.",
"Dive into tech in dropshipping research.",
"Get into tech in affiliate programs research.",
"Experiment with tech in online marketplaces research.",
"Dive into tech in mobile app marketing research.",
"Get into tech in content creation research.",
"Dive into tech in podcasting research.",
"Try tech in video blogging research.",
"Explore tech in livestreaming research.",
"Dive into tech in writing and blogging research.",
"Get into tech in graphic design research.",
"Dive into tech in illustration research.",
"Experiment with tech in animation research.",
"Learn about tech in 3D modeling research.",
"Dive into tech in motion graphics research.",
"Get into tech in typography research.",
"Experiment with tech in user interface design research.",
"Dive into tech in user experience design research.",
"Try tech in web design research.",
"Explore tech in app design research.",
"Dive into tech in game design research.",
"Get into tech in virtual reality design research.",
"Experiment with tech in augmented reality design research.",
"Dive into tech in architectural design research.",
"Get into tech in interior design research.",
"Dive into tech in fashion design research.",
"Try tech in industrial design research.",
"Explore tech in graphic arts research.",
"Dive into tech in textile design research.",
"Get into tech in jewelry design research.",
"Experiment with tech in product design research.",
"Learn about tech in automotive design research.",
"Dive into tech in graphic novels research.",
"Get into tech in comic book design research.",
"Dive into tech in illustration research.",
"Try tech in digital painting research.",
"Explore tech in fine arts research.",
"Dive into tech in music composition research.",
"Get into tech in audio production research.",
"Experiment with tech in music theory research.",
"Learn about tech in music history research.",
"Dive into tech in music education research.",
"Study tech in music performance research.",
"Try tech in music therapy research.",
"Dive into tech in theater production research.",
"Get into tech in acting research.",
"Experiment with tech in scriptwriting research.",
"Dive into tech in film direction research.",
"Get into tech in film editing research.",
"Dive into tech in cinematography research.",
"Study tech in animation production research.",
"Try tech in special effects research.",
"Dive into tech in 3D animation research.",
"Get into tech in stop-motion animation research.",
"Experiment with tech in CGI research.",
"Learn about tech in film scoring research.",
"Dive into tech in post-production research.",
"Study tech in documentary filmmaking research.",
"Try tech in wildlife filmmaking research.",
"Explore tech in sports broadcasting research.",
"Dive into tech in journalism research.",
"Get into tech in news reporting research.",
"Dive into tech in investigative journalism research.",
"Experiment with tech in photojournalism research.",
"Learn about tech in broadcast journalism research.",
"Dive into tech in documentary photography research.",
"Study tech in portrait photography research.",
"Try tech in fashion photography research.",
"Explore tech in wildlife photography research.",
"Dive into tech in landscape photography research.",
"Get into tech in underwater photography research.",
"Experiment with tech in aerial photography research.",
"Dive into tech in architectural photography research.",
"Get into tech in event photography research.",
"Try tech in product photography research.",
"Explore tech in food photography research.",
"Dive into tech in travel photography research.",
"Get into tech in street photography research.",
"Experiment with tech in astrophotography research.",
"Learn about tech in macro photography research.",
"Dive into tech in documentary photography research.",
"Get into tech in forensic photography research.",
"Experiment with tech in 3D modeling research.",
"Dive into tech in virtual sculpting research.",
"Learn a new programming language.",
"Build a website from scratch.",
"Try coding a mobile app.",
"Dive into a tech podcast.",
"Explore virtual reality experiences.",
"Master video editing skills.",
"Create digital art.",
"Tinker with Raspberry Pi projects.",
"Upgrade your computer's hardware.",
"Set up a smart home system.",
"Develop a game.",
"Experiment with 3D printing.",
"Learn about AI and machine learning.",
"Solve tech-related puzzles.",
"Explore cybersecurity topics.",
"Get into DIY electronics.",
"Try your hand at ethical hacking.",
"Build a custom PC.",
"Experiment with AR and VR apps.",
"Explore open-source software.",
"Explore blockchain technology.",
"Start a tech blog or vlog.",
"Participate in coding challenges.",
"Learn about quantum computing.",
"Set up a media server.",
"Dive into cloud computing.",
"Study data science.",
"Create a chatbot.",
"Experiment with IoT devices.",
"Learn about nanotechnology.",
"Contribute to open-source projects.",
"Explore the world of cryptocurrencies.",
"Read tech-related books.",
"Follow tech news and trends.",
"Set up a home lab.",
"Try out a tech-related MOOC.",
"Learn about UX/UI design.",
"Build a custom mechanical keyboard.",
"Study computer graphics.",
"Try your hand at algorithmic trading.",
"Explore the dark web (with caution).",
"Experiment with data visualization.",
"Study bioinformatics.",
"Get into software testing.",
"Learn about cloud security.",
"Explore the world of AI ethics.",
"Build a network-attached storage (NAS) system.",
"Learn about DevOps practices.",
"Experiment with web scraping.",
"Study IT project management.",
"Set up a home automation system.",
"Try competitive coding.",
"Learn about biohacking.",
"Build a gaming PC.",
"Explore the maker movement.",
"Study quantum cryptography.",
"Learn about 5G technology.",
"Try reverse engineering.",
"Explore virtual private networks (VPNs).",
"Study bioelectrics.",
"Get into 3D modeling.",
"Learn about space technology.",
"Study nanorobotics.",
"Dive into wearable tech.",
"Try cybersecurity competitions.",
"Experiment with augmented reality.",
"Learn about data mining.",
"Study robotics.",
"Get into digital marketing.",
"Explore the Internet of Things (IoT).",
"Dive into computer forensics.",
"Study cryptocurrency trading.",
"Try ethical hacking challenges.",
"Learn about blockchain development.",
"Explore space exploration tech.",
"Study biometric security.",
"Dive into green technology.",
"Get into quantum programming.",
"Experiment with machine learning models.",
"Learn about virtual currencies.",
"Study tech-related patents.",
"Try hardware overclocking.",
"Explore the history of computing.",
"Dive into DIY home automation.",
"Study quantum AI.",
"Learn about internet censorship.",
"Try your hand at PCB design.",
"Explore tech-related art.",
"Study the philosophy of technology.",
"Get into digital privacy.",
"Experiment with cyber-physical systems.",
"Learn about tech in healthcare.",
"Dive into tech startup ideas.",
"Study the impact of AI on society.",
"Try building a home server.",
"Explore tech in agriculture.",
"Learn about tech in education.",
"Dive into tech policy and regulations.",
"Study tech in sports.",
"Get into voice assistants and chatbots.",
"Experiment with AI-generated art.",
"Learn about tech in fashion.",
"Dive into tech in the automotive industry.",
"Study tech in renewable energy.",
"Try virtual tech events and expos.",
"Explore tech in food and cooking.",
"Learn about tech in finance.",
"Dive into tech in music and audio.",
"Study tech in transportation.",
"Get into tech for the elderly.",
"Experiment with tech in mental health.",
"Learn about tech in wildlife conservation.",
"Dive into tech in language translation.",
"Study tech in space travel.",
"Try tech in disaster response.",
"Explore tech in ocean exploration.",
"Study tech in renewable energy.",
"Dive into tech in agriculture.",
"Learn about tech in education.",
"Get into tech in healthcare.",
"Experiment with tech in gaming.",
"Study tech in architecture.",
"Dive into tech in fashion.",
"Learn about tech in art and design.",
"Try tech in sports and fitness.",
"Explore tech in photography.",
"Dive into tech in travel and tourism.",
"Study tech in astronomy.",
"Experiment with tech in weather forecasting.",
"Learn about tech in virtual museums.",
"Get into tech in archaeology.",
"Dive into tech in archaeology.",
"Study tech in wildlife conservation.",
"Try tech in environmental monitoring.",
"Explore tech in disaster management.",
"Dive into tech in humanitarian aid.",
"Study tech in wildlife tracking.",
"Get into tech in agriculture.",
"Experiment with tech in robotics.",
"Learn about tech in marine biology.",
"Dive into tech in geology.",
"Study tech in forestry.",
"Try tech in environmental education.",
"Explore tech in recycling.",
"Dive into tech in sustainability.",
"Study tech in wildlife photography.",
"Get into tech in ornithology.",
"Experiment with tech in botany.",
"Learn about tech in marine conservation.",
"Dive into tech in space exploration.",
"Study tech in physics research.",
"Try tech in chemistry research.",
"Explore tech in medical research.",
"Dive into tech in genetics research.",
"Study tech in psychology research.",
"Get into tech in social sciences research.",
"Experiment with tech in environmental research.",
"Learn about tech in neuroscience research.",
"Dive into tech in climate research.",
"Study tech in geological research.",
"Try tech in archaeological research.",
"Explore tech in astronomy research.",
"Dive into tech in materials science research.",
"Study tech in computer science research.",
"Get into tech in nanotechnology research.",
"Experiment with tech in robotics research.",
"Learn about tech in artificial intelligence research.",
"Dive into tech in machine learning research.",
"Study tech in data science research.",
"Try tech in quantum computing research.",
"Explore tech in cryptography research.",
"Dive into tech in cybersecurity research.",
"Study tech in cloud computing research.",
"Get into tech in network security research.",
"Experiment with tech in computer forensics research.",
"Learn about tech in information security research.",
"Dive into tech in ethical hacking research.",
"Study tech in web development research.",
"Try tech in software engineering research.",
"Explore tech in data analysis research.",
"Dive into tech in game development research.",
"Study tech in virtual reality research.",
"Get into tech in augmented reality research.",
"Experiment with tech in 3D printing research.",
"Learn about tech in computer graphics research.",
"Dive into tech in human-computer interaction research.",
"Study tech in natural language processing research.",
"Try tech in speech recognition research.",
"Explore tech in computer vision research.",
"Dive into tech in robotics research.",
"Study tech in machine vision research.",
"Get into tech in autonomous systems research.",
"Experiment with tech in automation research.",
"Learn about tech in internet of things (IoT) research.",
"Dive into tech in sensors and actuators research.",
"Study tech in nanotechnology research.",
"Try tech in quantum technology research.",
"Explore tech in biotechnology research.",
"Dive into tech in renewable energy research.",
"Study tech in space technology research."
    ];

    function getRandomActivity() {
      var randomIndex = Math.floor(Math.random() * techActivities.length);
      return techActivities[randomIndex];
    }

    var generateButton = document.getElementById("generateButton");
    var activityDiv = document.getElementById("activity");

    generateButton.addEventListener("click", function() {
      var randomActivity = getRandomActivity();
      activityDiv.textContent = randomActivity;
    });